---
title: "Final Writeup Draft"
output: html_document
date: "2026-04-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Motivation Question
Should Answer: "Choose one of the variables in your cleaned dataset to be the target of prediction.  You should be able to explain why a policymaker, business executive, or another member of the general public might find it useful to be able to predict this outcome variable."

##Motivation Content
A recession is usually defined as two consecutive quarters of negative GDP growth.  More generally, recessions (or similar events) may be thought of as when the economy goes beyond "slowing down" and begins shrinking in some aspect.  This is, or should be, of interest to almost every economic agent, from policymakers and business leaders to households and individuals -- a recession can have many impacts, but may generally be classified into two categories, either an "financial crisis," or a "labor recession."  It is clear that a financial crisis is of interest to everyone with assets -- if the value of assets is decreasing, then it is reasonable to expect that there will be massive income effects as these agents "feel poorer" and respond rationally.  If there is a labor recession,  households are likely to struggle to provide enough labor to satisfy their needs, and policymakers would like to mitigate this.

Existing predictors of recessions are commonly flawed and overfit -- there is a saying that "economists have predicted 11 of the last 5 recessions," and this stems from this overfitting, which commonly takes a single (or a relatively small number) indicator variable and identify some condition which has occurred prior to most or all of the recessions observed in the United States.  Perhaps the most famous of these is the inversion of the yield curve on US treasury notes -- this may occur prior to most or all recessions, but it is a sentiment-based indicator, rather than a structural indicator.  Futher, this is imprecise as an indicator, and it is commonly referenced as indicating a recession sometime in the next 6-12 months.  This presents some obvious issues, as with regular false positives and such an uncertain timeline, preparatory or preventative actions can not be reasonably taken based on this signalling.

It is not particularly obvious how a good predictor might be constructed; one of the most significant challenges is the lack of data -- not in the sense that we lack historical economic data, but rather that recessions occur somewhat infrequently.  This infrequent occurrence of recessions makes any attempt at predicting them subject to the same flaws in existing indicators: overfitting and false positives.  Despite that flaw, some robustness can be constructed, with out-of-sample testing, and this is a necessary characteristic of the machine learning methods we use.

## Introduction; PH and Wasserstein distance, ROC and AUC evaluation

In this project, we use two techniques which have not been assimilated into mainstream empirical economics, though they are used in a variety of other data analysis applications -- asset price modeling prominent among them.  These techniques are the use of Persistent Homology (PH) and building from that, the Wasserstein distance.  PH is a tool which models the "shape" of data, that is, how the discrete data points are embedded in a high dimensional manifold in space, and allows for unsupervised clustering and structuring of data points.  Wasserstein distance, commonly referenced as the "earth-mover's distance" is a measure of optimal transport between two structures, the minimal amount of "material-distance" which must be changed to convert one structure to the other.  In a physics sense, this is a measure of work, and in a more purely mathematical sense, it functions as a topological derivative -- the rate of change between topological states.

In a little more detail, PH studies emergent structures in the data, and at what observational scale these structures exist.  It does this by setting a ball of radius $r$ around each point in space, then varying the size of $r$.  When these balls overlap, an edge is added between them.  This forms a graph, where the data points are the vertices, and the edges are a function of the size of the radius. If PH is taken further, there are additional degrees where it may be extended: if three points are fully connected, then they enclose a triangular "face", and if four points are fully connected, then they enclose a tetrahedronal volume.  This space filling volume may be taken to whatever extent desired, and this is the study of simplicial complexes.  For the purpose of this study, we stop at the two-dimensional faces, so consider only the edges and faces.

The Wasserstein distance, as described earlier, is the minimal cost of transforming one structure into another.  It is clear then, that the value of this measure depends on the structures it is comparing -- we create a time series of this distance, as we move a window of length $k$ along the data, creating PH structures for windows containing time steps $1:k, 2:(k+1), ... , n:(n+k-1)$.  The overlap in these windows means that measuring the distance between consecutive structures is a measure of the difference in influence of the oldest (exiting) point and the newest (entering) point.  If these points are identical, the PH structures are identical, and the distance is zero.  If these points are strongly influential in different aspects, then this distance is very large.  It is our hypothesis that this distance will act as an edge detector between states, and in particular, the entry or exit from a recessionary economic state.

Given the above methodology, we use Receiver Operating Characteristic (ROC) analysis and Area Under the Curve (AUC) as evaluation metrics.  ROC compares the false positive and true positives of a binary classifier -- so for this metric, some threshold $\tau$ is chosen for the Wasserstein metric, and if the Wasserstein metric is greater than $\tau$ then a recession is signalled.  Then, this charts the sensitivity (the rate of true positives) on the Y-axis and the complement of the specificity (the rate of false positives) on the X-axis.  This curve will necessarily form an arc between (0,0), where the model detects no recessions (due to a threshohld set too high) and (1,1), where the model signals everything as a recession (due to a threshold set too low).  Then, assuming a symmetric cost of misclassification, the optimal threshold value $\tau^*$ is chosen as the $\tau$ corresponding to the point on this curve closest to (0,1), for perfect detection of true positives without any false indications.  

The AUC is the area under the ROC.  It measures the overall quality of the signal from this model, on a scale from 0 to 1 -- we can interpret this as the probability that this model will assign a higher Wasserstein distance to a recessionary window than to an non-recessionary window.  This should be within the interval $(0.5, 1)$, because if it is worse than random, we would simply invert the signal.  This metric is less sensitive to the potential to "get lucky" with careful selection of the threshold $\tau$ than many alternatives, because it considers all thresholds, and the power of the model over all variations of this parameter.  Further, as a metric derived from ROC, the AUC is invariant on the partition of the data between classes, and so will not be artificially inflated by an imbalance between them in the training data.


##Methods Question 1
Should Answer: "Use other variables in your cleaned dataset to predict the outcome variable as best you can.  Follow all the correct ML practices: Set aside a test set; train and predict using one or more ML algorithms; tune your model(s) using appropriate cross-validation, and finally test your performance with the held-out data.  (Don't cheat!!! Really, don't touch the test set until you are done tweaking your model.  If you change your model after seeing how it does in the test set, then you are reporting dishonest performance numbers.)"

##Methods Question 2
Should Answer: "Explain your methods: What learning method did you use?  What parameters did you tune?  What method did you use for tuning?"

##Methods Content


##Results Question
Should Answer: "Interpret your results: How did you measure performance/success?  How did your model(s) perform?  What do you think limited the performance?  What did you learn in the process?  It may be effective to crease visualizations to accompany your interpretation."